# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  dockerhub:
    type: docker-registry
    url: https://registry.hub.docker.com
    username: ${{secrets.DOCKER_HUB_USERNAME}}
    password: ${{secrets.DOCKER_HUB_PASSWORD}}
    replaces-base: true
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directories:
      - "/images/*"
    registries: "*"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "images"
